# permissions for end users to edit virtualclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualcluster-editor-role
rules:
- apiGroups:
  - vcluster.zacharyseguin.ca
  resources:
  - virtualclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vcluster.zacharyseguin.ca
  resources:
  - virtualclusters/status
  verbs:
  - get
