# permissions for end users to view virtualclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualcluster-viewer-role
rules:
- apiGroups:
  - vcluster.zacharyseguin.ca
  resources:
  - virtualclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vcluster.zacharyseguin.ca
  resources:
  - virtualclusters/status
  verbs:
  - get
