## Append samples you want in your CSV to this file as resources ##
resources:
- vcluster_v1alpha1_cluster.yaml
- vcluster_v1alpha1_virtualcluster.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
